# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [5]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [6]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print("Dimension:", A.ndim) 
print("Shape:", A.shape) 
print("Size:", A.size)
print("Data type:", A.dtype) 

Dimension: 2
Shape: (3, 5)
Size: 15
Data type: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [13]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("B: ")
print(B)
print()
print("C: ")
print(C)

B: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

C: 
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [42]:
subtraction = B - C 
print("Elementwise subtraction")
print()
print(subtraction)


Elementwise subtraction

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [17]:
multiplication = B * C 
print("Elementwise multiplication")
print()
print(multiplication)

Elementwise multiplication

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [16]:
matrix_multiplication = B @ C
print("Matrix multiplication")
print()
print(matrix_multiplication)


Matrix multiplication

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [18]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
Exponent = np.exp(B)
print("Exponent_value: ")
print()
print(Exponent)

Exponent_value: 

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [46]:
min_value = np.min(B)
print("Minimum value in B:", min_value)

Minimum value in B: 1


In [21]:
min_rows = np.min(B, axis=1)
print("Minimum value in each row:", min_rows)

Minimum value in each row: [1 4 7]


In [22]:
min_column = np.min(B, axis=0)
print("Minimum value in each column:", min_column)

Minimum value in each column: [1 2 3]


In [23]:
min_index = np.argmin(B)
print("Index of the minimum value:", min_index)

Index of the minimum value: 0


In [24]:
min_index_rows = np.argmin(B, axis=1)
print("Index of the minimum value in each row:", min_index_rows)

Index of the minimum value in each row: [0 0 0]


In [25]:
sum_all_elements = np.sum(B)
print(sum_all_elements)

45


In [26]:
mean_column = np.mean(B, axis=0)
print(mean_column)

[4. 5. 6.]


In [27]:
median_column = np.median(B, axis=0)
print(median_column)

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [33]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [32]:
# It means that NumPy complets the remaining indices on the second row A[1] along the missing axes (column).

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [7]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
# Ett sätt att göra det är att använda np.flat funktionen.
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [47]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#The code prints out a 3D dimension array upto 29. 2 specifies the number of layers, 3 represents the number of rows while -1 allows numpy to reshape the remaining dimension (column).

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [37]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [38]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [39]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:
def add_mult_matrices(matrix1, matrix2, operation):

    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Inputs must be of type numpy.ndarray")

    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same dimension size")
        return np.add(matrix1, matrix2)

    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Operation failed. Number of columns in the first matrix must be equal to the number of rows in the second matrix.")
        return np.multiply(matrix1, matrix2)


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

#### Upggift 10.1.1

In [ ]:
# A) Vilken dimension har x = (4, 3)
# X har dimensionen 1 x 2 vilket betyder att den har en enda rad och två kolumner.

In [1]:
x = (4, 3)
# B) Beräkna 5x?
result = tuple(5 * i for i in x)
result

(20, 15)

In [2]:
# D) Beräkna 5x + 3x?
result = tuple((5 + 3) * i for i in x)
result

(32, 24)

In [3]:
# E) Beräkna 8x?
result = tuple(8 * i for i in x)
result

(32, 24)

In [4]:
# F) Beräkna 4x - x?
result = tuple((4 - 1) * i for i in x)
result

(12, 9)

In [4]:
# G) Beräkna x^T?
x = np.array([4, 3])
x_transponat = x.reshape(-1, 1)
x_transponat
#Den nya dimensionen blir 2 x 1, alltså två rader och en kolumn.

array([[4],
       [3]])

In [ ]:
# H) HÄr x + x^T definierat?
# Funktionen är inte definierat eftersom dimensionerna i båda inte är samma. X har dimensionen 1 x 2 medan x^T har dimensionen 2 x 1.


In [5]:
# I) Beräkna ||X||?
normen_x = np.linalg.norm(x)
normen_x

5.0

#### Upggift 10.1.2

In [15]:
# Definiera vektorn v enligt nedan
v = np.array([[3], [7], [0], [11]])
v
# a) Vektorn har dimension 4 x 1 eftersom den har 4 rader och en kolumn.


array([[ 3],
       [ 7],
       [ 0],
       [11]])

In [17]:
# b) Beräkna 2v?
result = 2 * v
result

array([[ 6],
       [14],
       [ 0],
       [22]])

In [19]:
# c) Beräkna 5v + 2v?
result = 5 * v + 2 * v
result

array([[21],
       [49],
       [ 0],
       [77]])

In [20]:
# d) Beräkna 4v - 2v?
result = 4 * v - 2 * v
result

array([[ 6],
       [14],
       [ 0],
       [22]])

In [28]:
# e) Beräkna v^T?
v_transponat = v.reshape(1, -1)
v_transponat
# Vektorn fick en 1 x 4 dimension istället för en 4 x 1 dimension.

array([[ 3,  7,  0, 11]])

In [29]:
# f) Beräkna ||V||?
normen_v = np.linalg.norm(v)
normen_v

13.379088160259652

#### Uppgift 10.1.3. 

In [37]:
# a) Beräkna ∥v1∥?
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

normen_v1 = np.linalg.norm(v1)
normen_v1


7.14142842854285

In [36]:
# b) Beräkna ∥v1 − v2∥?
subtraktion = v1 - v2
normen_subtraktion = np.linalg.norm(subtraktion)
normen_subtraktion

4.47213595499958

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

#### Uppgift 10.2.1 - Definiera matriserna:


In [28]:
A = np.array([[2, 1, -1],[1, -1, 1]])

B = np.array([[4, -2, 1],[2, -4, -2]])

C = np.array([[1, 2],[2, 1]])

D = np.array([[3, 4],[4, 3]])

E = np.array([[1],[2]])

I = np.array([[1, 0],[0, 1]])

In [36]:
# a) 2A
result_A = 2 * A

# b) B - 2A
result_B = B - result_A

# C) 3C - 2E
result_C = 3 * C - 2 * E

# D) 2D - 3C
result_D = 2 * D - 3 * C

# E) D^T + 2D
result_E = D.T + 2 * D

# F) 2C^T - 2D^T
result_F = 2 * C.T - 2 * D.T

# G) A^T - B
# Funktionen är inte definierat eftersom matriserna inte har samma dimensioner.

# H) AC
# Matrisen är inte definierat eftersom antal kolumner i A inte överensstämmer med antal rader i C.

# I) CD
result_I = C @ D

# J) CB
result_J = C @ B

# K) CI
result_K = C @ I

# L) AB^T
result_L = A @ B.T

print("A:\n", result_A)
print("B:\n", result_B)
print("C:\n", result_C)
print("D:\n", result_D)
print("E:\n", result_E)
print("F:\n", result_F)
print("I:\n", result_I)
print("J:\n", result_J)
print("K:\n", result_K)
print("L:\n", result_L)

A:
 [[ 4  2 -2]
 [ 2 -2  2]]
B:
 [[ 0 -4  3]
 [ 0 -2 -4]]
C:
 [[ 1  4]
 [ 2 -1]]
D:
 [[3 2]
 [2 3]]
E:
 [[ 9 12]
 [12  9]]
F:
 [[-4 -4]
 [-4 -4]]
I:
 [[11 10]
 [10 11]]
J:
 [[  8 -10  -3]
 [ 10  -8   0]]
K:
 [[1 2]
 [2 1]]
L:
 [[5 2]
 [7 4]]


#### Uppgift 10.2.2. - Definiera matrisen

In [39]:
A = np.array([[2, 3, 4],[5, 4, 1]])

result = A @ A.T
result

array([[29, 26],
       [26, 42]])

#### Uppgift 10.2.3. - Definiera matriserna


In [47]:
A = np.array([[1, 2],[2, 4]])
B = np.array([[2, 1],[1, 3]])
C = np.array([[4, 3],[0, 2]])

AB = A @ B
AC = A @ C

print("AB:\n", AB)
print("AC:\n", AC)
print("B = C?:\n", np.array_equal(B, C)) 
# Vi kan se att AB matrisen är lika med AC matrisen.
# Med hjälp av den inbyggda funktionen np.array_equal kan vi ta reda på om B är lika med C.

AB:
 [[ 4  7]
 [ 8 14]]
AC:
 [[ 4  7]
 [ 8 14]]
B = C?:
 False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [49]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [50]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [51]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
